# This file is used to configure the PagesCMS interface.
# For more information, see: https://pagescms.org/docs/configuration/

media:
  input: "assets/img"
  output: "/assets/img"

content:
  - name: "home"
    label: "Home Page"
    path: "_data/home.yml"
    type: "file"
    fields:
      - name: "hero"
        label: "Hero Section"
        type: "object"
        fields:
          - { name: "image", label: "Image", type: "image" }
          - { name: "title", label: "Title", type: "string" }
          - { name: "subtitle", label: "Subtitle", type: "string" }
          - { name: "description", label: "Description", type: "text" }
      - name: "feature_cards"
        label: "Feature Cards"
        type: "object"
        list:
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "icon", label: "Icon Class", type: "string" }
          - { name: "content", label: "Content", type: "text" }
          - { name: "link", label: "Link", type: "string" }
          - { name: "link_text", label: "Link Text", type: "string" }
          - { name: "link_icon", label: "Link Icon", type: "string" }

  - name: "research"
    label: "Research Page"
    path: "_data/research.yml"
    type: "file"
    fields:
      - name: "research_areas"
        label: "Research Areas"
        type: "object"
        list:
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "icon", label: "Icon Class (e.g. fas fa-infinity)", type: "string" }
          - { name: "content", label: "Content", type: "rich-text" }

  - name: "publications"
    label: "Publications"
    path: "_data/publications.yml"
    type: "file"
    fields:
      - name: "publications"
        label: "Publications List"
        type: "object"
        list:
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "mr_number", label: "MR Number", type: "string" }
          - { name: "title", label: "Title (Both)", type: "string" }
          - { name: "authors", label: "Authors (Both)", type: "string" }
          - { name: "journal_details", label: "Journal Details (Both)", type: "string" }
          - { name: "status", label: "Status (Both)", type: "select", options: { values: ["Preprint", "Journal Article", "Book", "Submitted", "Other"] } }
          - { name: "msc_code", label: "MSC Code (Subpage Only)", type: "string" }
          - { name: "type", label: "Type (Both)", type: "select", options: { values: ["Article", "Book", "Other"] } }
          - { name: "reviewer", label: "Reviewer (Subpage Only)", type: "string" }
          - { name: "citation_count", label: "Citation Count (Subpage Only)", type: "number" }
          - { name: "publisher_details", label: "Publisher Details (Subpage Only)", type: "string" }
          - { name: "isbn", label: "ISBN (Subpage Only)", type: "string" }
          - { name: "appendix", label: "Appendix (Subpage Only)", type: "string" }
          - { name: "body", label: "Content / Abstract (Subpage Only)", type: "rich-text" }
          - name: "links"
            label: "Links"
            type: "object"
            list:
              collapsible:
                summary: "{fields.label}"
                collapsed: true
            fields:
              - { name: "label", label: "Label", type: "string" }
              - { name: "url", label: "URL", type: "string" }
          - name: "pdfs"
            label: "PDFs"
            type: "object"
            list:
              collapsible:
                summary: "{fields.label}"
                collapsed: true
            fields:
              - { name: "label", label: "Label", type: "string" }
              - { name: "file", label: "File", type: "file" }
      - name: "software"
        label: "Software Packages"
        type: "object"
        list:
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "description", label: "Description", type: "text" }
          - { name: "author", label: "Author", type: "string" }
          - { name: "link", label: "Link URL", type: "string" }
          - { name: "link_text", label: "Link Text", type: "string" }
          - { name: "thesis", label: "Thesis URL (Optional)", type: "string" }

  - name: "teaching"
    label: "Teaching"
    path: "_data/teaching.yml"
    type: "file"
    fields:
      - name: "courses"
        label: "Courses by Year"
        type: "object"
        list:
          collapsible:
            summary: "{fields.year}"
            collapsed: true
        fields:
          - { name: "year", label: "Year", type: "number" }
          - name: "semesters"
            label: "Semesters"
            type: "object"
            list:
              collapsible:
                summary: "{fields.semester}"
                collapsed: true
            fields:
              - { name: "semester", label: "Semester Name", type: "string" }
              - name: "courses"
                label: "Courses"
                type: "object"
                list:
                  collapsible:
                    summary: "{fields.title}"
                    collapsed: true
                fields:
                  - { name: "title", label: "Course Title (Both)", type: "string" }
                  - { name: "instructor", label: "Instructor (Both)", type: "string" }
                  - { name: "course_type", label: "Course Type (Subpage Only)", type: "select", options: { values: ["Lecture", "Seminar", "Proseminar", "Exercise", "Other"] } }
                  - { name: "description", label: "Description (Both)", type: "text" }
                  - name: "links"
                    label: "Links (Both)"
                    type: "object"
                    list:
                      collapsible:
                        summary: "{fields.label}"
                        collapsed: true
                    fields:
                      - { name: "label", label: "Label", type: "string" }
                      - { name: "url", label: "URL", type: "string" }
                  - name: "pdfs"
                    label: "PDFs (Both)"
                    type: "object"
                    list:
                      collapsible:
                        summary: "{fields.label}"
                        collapsed: true
                    fields:
                      - { name: "label", label: "Label", type: "string" }
                      - { name: "file", label: "File", type: "file" }
                  - { name: "body", label: "Course Details (Subpage Only)", type: "rich-text" }

  - name: "members"
    label: "Members"
    path: "_data/members.yml"
    type: "file"
    fields:
      - name: "sections"
        label: "Member Sections"
        type: "object"
        list:
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "title", label: "Section Title", type: "string" }
          - { name: "layout", label: "Layout Style", type: "select", options: { values: ["big", "medium", "small"], labels: ["Big (Highlight)", "Medium (Standard)", "Small (Compact)"] }, default: "medium" }
          - name: "members"
            label: "Members"
            type: "object"
            list:
              collapsible:
                summary: "{fields.name}"
                collapsed: true
            fields:
              - { name: "name", label: "Name (Both)", type: "string", required: true }
              - { name: "role", label: "Role (Both)", type: "string" }
              - { name: "group", label: "Group (Both)", type: "select", options: { values: ["Head", "Secretary", "Members", "Former Members"] }, default: "Members", hidden: true }
              - { name: "photo", label: "Photo (Both)", type: "image" }
              - { name: "description", label: "Short Description (Card) (Main Page Only)", type: "rich-text" }
              - { name: "email", label: "Email (Subpage Only)", type: "string" }
              - { name: "publication_name", label: "Publication Name Match (e.g. 'Böckle')", type: "string" }
              - name: "aliases"
                label: "Name Aliases (e.g. 'C.V. Sriram')"
                type: "list"
                field: { type: "string" }
              - { name: "cv", label: "CV (PDF) (Subpage Only)", type: "file" }
              - { name: "phone", label: "Phone (Subpage Only)", type: "string" }
              - { name: "fax", label: "Fax (Subpage Only)", type: "string" }
              - { name: "room", label: "Room (Subpage Only)", type: "string" }
              - { name: "office_hours", label: "Office Hours (Subpage Only)", type: "string" }
              - name: "research_interests"
                label: "Research Interests (Subpage Only)"
                type: "list"
                field: { type: "string" }
              - name: "education"
                label: "Education (Subpage Only)"
                type: "object"
                list:
                  collapsible:
                    summary: "{fields.degree} - {fields.institution}"
                    collapsed: true
                fields:
                  - { name: "year", label: "Year/Period", type: "string" }
                  - { name: "degree", label: "Degree/Position", type: "string" }
                  - { name: "institution", label: "Institution", type: "string" }
              - { name: "body", label: "Biography / Full Profile (Subpage Only)", type: "rich-text" }
              - name: "selected_publications"
                label: "Selected Publications (Subpage Only)"
                type: "object"
                list:
                  collapsible:
                    summary: "{fields.title}"
                    collapsed: true
                fields:
                  - { name: "title", label: "Title", type: "string" }
                  - { name: "authors", label: "Authors", type: "string" }
                  - { name: "journal", label: "Journal/Details", type: "string" }
                  - { name: "link", label: "Link URL", type: "string" }
              - name: "theses"
                label: "Theses (Subpage Only)"
                type: "object"
                list:
                  collapsible:
                    summary: "{fields.title}"
                    collapsed: true
                fields:
                  - { name: "title", label: "Title", type: "string" }
                  - { name: "author", label: "Author", type: "string" }
                  - { name: "type", label: "Type (e.g. PhD Thesis)", type: "string" }
                  - { name: "institution", label: "Institution", type: "string" }
                  - { name: "year", label: "Year", type: "string" }
                  - { name: "file", label: "File", type: "file" }
              - name: "links"
                label: "Social Links (Subpage Only)"
                type: "object"
                list:
                  collapsible:
                    summary: "{fields.text}"
                    collapsed: true
                fields:
                  - { name: "url", label: "URL", type: "string" }
                  - { name: "icon", label: "Icon Class (e.g. fas fa-globe)", type: "string" }
                  - { name: "text", label: "Link Text", type: "string" }

  - name: "links"
    label: "Links Page"
    path: "_data/links.yml"
    type: "file"
    fields:
      - name: "groups"
        label: "Link Groups"
        type: "object"
        list:
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "title", label: "Group Title", type: "string" }
          - { name: "icon", label: "Icon Class", type: "string" }
          - name: "links"
            label: "Links"
            type: "object"
            list:
              collapsible:
                summary: "{fields.title}"
                collapsed: true
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "url", label: "URL", type: "string" }

  - name: "contact"
    label: "Contact Page"
    path: "_data/contact.yml"
    type: "file"
    fields:
      - name: "address"
        label: "Address"
        type: "object"
        list:
          min: 1
          max: 1
          collapsible:
            summary: "{fields.title}"
            collapsed: true
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "institution", label: "Institution", type: "string" }
          - { name: "university", label: "University", type: "string" }
          - { name: "street", label: "Street", type: "string" }
          - { name: "city", label: "City", type: "string" }
          - { name: "country", label: "Country", type: "string" }
          - { name: "description", label: "Description", type: "text" }
          - { name: "map_url", label: "Map URL", type: "string" }
      - name: "contact_details"
        label: "Contact Details"
        type: "object"
        list:
          min: 1
          max: 1
          collapsible:
            summary: "{fields.phone}"
            collapsed: true
        fields:
          - { name: "phone", label: "Phone", type: "string" }
          - { name: "phone_hours", label: "Phone Hours", type: "string" }
          - { name: "fax", label: "Fax", type: "string" }
          - { name: "fax_note", label: "Fax Note", type: "string" }
          - { name: "general_info", label: "General Info", type: "text" }
      - name: "email"
        label: "Email Section"
        type: "object"
        list:
          min: 1
          max: 1
          collapsible:
            summary: "{fields.address}"
            collapsed: true
        fields:
          - { name: "intro", label: "Intro Text", type: "text" }
          - { name: "address", label: "Email Address", type: "string" }
          - { name: "outro", label: "Outro Text", type: "text" }


