# This file is used to configure the PagesCMS interface.
# For more information, see: https://pagescms.org/docs/configuration/

media:
  input: "assets/img"
  output: "/assets/img"

content:
  - name: "publications"
    label: "Publications"
    path: "_data/publications.yml"
    type: "file"
    fields:
      - name: "publications"
        label: "Publications"
        type: "list"
        fields:
          - { name: "mr_number", label: "MR Number", type: "string" }
          - { name: "title", label: "Title", type: "string" }
          - { name: "authors", label: "Authors", type: "string" }
          - { name: "journal_details", label: "Journal Details", type: "string" }
          - { name: "status", label: "Status", type: "string" }
          - { name: "msc_code", label: "MSC Code", type: "string" }
          - { name: "type", label: "Type", type: "string" }
          - { name: "reviewer", label: "Reviewer", type: "string" }
          - { name: "citation_count", label: "Citation Count", type: "number" }
          - { name: "publisher_details", label: "Publisher Details", type: "string" }
          - { name: "isbn", label: "ISBN", type: "string" }

  - name: "members"
    label: "Members"
    path: "_data/members.yml"
    type: "file"
    fields:
      - name: "sections"
        label: "Member Sections"
        type: "list"
        fields:
          - { name: "title", label: "Section Title", type: "string" }
          - name: "members"
            label: "Members"
            type: "list"
            fields:
              - { name: "name", label: "Name", type: "string" }
              - { name: "role", label: "Role", type: "string" }
              - { name: "photo", label: "Photo URL", type: "image" }
              - { name: "description", label: "Description", type: "text" }
              - name: "links"
                label: "Links"
                type: "list"
                fields:
                  - { name: "url", label: "URL", type: "string" }
                  - { name: "icon", label: "Icon (e.g., 'fas fa-envelope')", type: "string" }
                  - { name: "text", label: "Link Text", type: "string" }

  - name: "teaching"
    label: "Teaching"
    path: "_data/teaching.yml"
    type: "file"
    fields:
      - name: "courses"
        label: "Courses by Year"
        type: "list"
        fields:
          - { name: "year", label: "Year", type: "number" }
          - name: "semesters"
            label: "Semesters"
            type: "list"
            fields:
              - { name: "semester", label: "Semester", type: "string" }
              - name: "courses"
                label: "Courses"
                type: "list"
                fields:
                  - { name: "title", label: "Course Title", type: "string" }
                  - { name: "instructor", label: "Instructor", type: "string" }
                  - { name: "course_type", label: "Course Type", type: "string" }
                  - { name: "description", label: "Description", type: "text" }
                  - name: "links"
                    label: "Links"
                    type: "list"
                    fields:
                      - { name: "label", label: "Label", type: "string" }
                      - { name: "url", label: "URL", type: "string" }
                  - name: "pdfs"
                    label: "PDFs"
                    type: "list"
                    fields:
                      - { name: "label", label: "Label", type: "string" }
                      - { name: "file", label: "File Path", type: "file" }

  - name: "home"
    label: "Home Page"
    path: "_pages/home.md"
    type: "file"
    format: "yaml-frontmatter"
    fields:
      - { name: "layout", label: "Layout", type: "string", default: "page", hidden: true }
      - { name: "permalink", label: "Permalink", type: "string", default: "/home/", hidden: true }
      - { name: "nav", label: "Show in Navigation", type: "boolean" }
      - { name: "nav_order", label: "Navigation Order", type: "number" }
      - { name: "show_title", label: "Show Title", type: "boolean" }
      - { name: "title", label: "Title", type: "string" }
      - { name: "body", label: "Page Content", type: "rich-text" }

  - name: "contact"
    label: "Contact Page"
    path: "_pages/contact.md"
    type: "file"
    format: "yaml-frontmatter"
    fields:
      - { name: "layout", label: "Layout", type: "string", default: "page", hidden: true }
      - { name: "title", label: "Title", type: "string" }
      - { name: "permalink", label: "Permalink", type: "string", default: "/contact/", hidden: true }
      - { name: "nav", label: "Show in Navigation", type: "boolean" }
      - { name: "nav_order", label: "Navigation Order", type: "number" }
      - { name: "body", label: "Page Content", type: "rich-text" }

  - name: "research"
    label: "Research Page"
    path: "_pages/research.md"
    type: "file"
    format: "yaml-frontmatter"
    fields:
      - { name: "layout", label: "Layout", type: "string", default: "page", hidden: true }
      - { name: "permalink", label: "Permalink", type: "string", default: "/research/", hidden: true }
      - { name: "nav", label: "Show in Navigation", type: "boolean" }
      - { name: "nav_order", label: "Navigation Order", type: "number" }
      - { name: "show_title", label: "Show Title", type: "boolean" }
      - { name: "title", label: "Title", type: "string" }
      - { name: "body", label: "Page Content", type: "rich-text" }
